<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <rect x="17.5" y="30" width="15" height="40" fill="#420457">
        <animate attributeName="y" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="18;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.3278688524590164s"></animate>
        <animate attributeName="height" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="64;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.3278688524590164s"></animate>
    </rect>
    <rect x="42.5" y="30" width="15" height="40" fill="#5a3faa">
        <animate attributeName="y" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="20.999999999999996;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1639344262295082s"></animate>
        <animate attributeName="height" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="58.00000000000001;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1639344262295082s"></animate>
    </rect>
    <rect x="67.5" y="30" width="15" height="40" fill="#708adc">
        <animate attributeName="y" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="20.999999999999996;30;30" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate>
        <animate attributeName="height" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="58.00000000000001;40;40" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate>
    </rect>
<!-- [ldio] generated by https://loading.io/ --></svg>
